package ch02;
import becker.robots.*;

/**
 * 
 * @author arq
 *
 */
public class WriterBot extends RobotSE {
	public WriterBot(City aCity, int aStreet, int anAvenue, Direction aDirection, int things) {
		super(aCity, aStreet, anAvenue, aDirection, things);		
	}
	public void letterH() {
		this.move();
		this.turnLeft();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnAround();
		this.move(2);
		this.turnLeft();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnLeft();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnAround();
		this.move(3);
		this.putThing();
		this.move();
		this.putThing();
		this.turnLeft();
		this.move();
	}
	public void letterE() {
		this.move(3);
		this.turnAround();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnRight();
		this.move();
		this.putThing();
		this.move();
		this.turnRight();
		this.move(2);
		this.turnAround();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnRight();
		this.move();
		this.putThing();
		this.move();
		this.turnRight();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnRight();
		this.move(4);
		this.turnLeft();
		this.move();		
	}
	public void letterL() {
		this.move(3);
		this.turnAround();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnRight();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnRight();
		this.move(3);
		this.turnRight();
		this.move(4);
		this.turnLeft();
	}
	public void letterO() {
		this.move(3);
		this.turnAround();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnRight();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnRight();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnRight();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.move();
		this.putThing();
		this.turnLeft();
		this.move();
	}
}
